name: Test Action Matrix - User

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    strategy:
      matrix:
        users: [ 'Alice', 'Bob', 'Charlie' ]
    uses: ./.github/workflows/matrix-reusable-workflow.yml
    with:
      user: ${{ matrix.users }}
